services:
  postgresql_zz:  # Nome do serviço
    image: 'postgres:17.0'
    container_name: postgresql_zz
    environment:
      POSTGRES_USER: source_admin
      POSTGRES_PASSWORD: source_admin
    ports:
      - '5432:5432'
    volumes:
      - './database-sources/postgresql_zz:/var/lib/postgresql/data'
volumes:
  postgresql_data:
    driver: local
