services:
    postgresql_zz:
        image: 'postgres:17.0'
        container_name: postgresql_zz
        environment:
            POSTGRES_USER: source_admin
            POSTGRES_PASSWORD: source_admin
            POSTGRES_DB: zz_enterprise
        ports:
            - '5432:5432'
        volumes:
            - '${HOME}/pyetl_zz/data/postgre_zz:/var/lib/postgresql/data'
